### ISSUE TITLE
How to run the codes in examples?

### ISSUE THREAD

**Issue by ariesdevil** [rajasekarv/native_spark#11]
I create a `test_native_spark` project and copy codes in `make_rdd.rs` to the project's `main.rs`
Then run this project using `cargo +nightly-2019-09-11 run` got some errors:
```
thread 'main' panicked at 'Unable to open the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
How can I solve this?

**Comment by rajasekarv** [comment]
First, Install [Cap'n Proto](https://capnproto.org/install.html)
Then, run these following steps for local mode:(Tested only on Linux) 
1.` git clone https://github.com/rajasekarv/native_spark/`
2. `cd native_spark`
3. copy hosts.conf file in config_files directory to your home directory. `cp config_files/hosts.conf ~/hosts.conf`
4. `export SPARK_LOCAL_IP=0.0.0.0`
5. `cargo run --example make_rdd`

Note: Initial build time can be very long. In my machine, it takes around 3 mins just for debug build. 
If it is still not working, let me know.

**Comment by ariesdevil** [comment]
It works.
