### ISSUE TITLE
how about flink

### ISSUE THREAD

**Issue by walter211** [rajasekarv/native_spark#31]

**Comment by rajasekarv** [comment]
@walter211  I didn't get what this is about? Can you please  eloborate?

**Comment by Yanwenjiepy** [comment]
Apache Flink is a framework and distributed processing engine for stateful computations over unbounded and bounded data streams. Flink has been designed to run in all common cluster environments, perform computations at in-memory speed and at any scale.

Flink's  url: https://flink.apache.org/


In my opinion, flink is a copy and customized upgrade to spark.

**Comment by rajasekarv** [comment]
I wouldn't say Flink is a copy of Spark. It has a very different architecture when compared to Spark. Typical iterative ML algorithms are much nicer to implement in Flink than in Spark. Regardless of these, I still didn't understand what this issue is about?

**Comment by rajasekarv** [comment]
If there is nothing more to add, I am closing this issue. Feel free to reopen it anytime with more description.
