### ISSUE TITLE
build failed!! 

### ISSUE THREAD

**Issue by errord** [rajasekarv/native_spark#42]
errorddeMacBook-Pro:native_spark d$ cargo build
   Compiling native_spark v0.1.0 (/Users/d/Work/opensource/native_spark)
   Compiling bincode v1.2.0
   Compiling serde_closure v0.2.7
   Compiling rustc_version v0.2.3
error: failed to run custom build command for `native_spark v0.1.0 (/Users/d/Work/opensource/native_spark)`

Caused by:
  process didn't exit successfully: `/Users/d/Work/opensource/native_spark/target/debug/build/native_spark-3382f7e3c05897a6/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'capnpc compiling issue: Error { kind: Failed, description: "Error while trying to execute `capnp compile`: Failed: No such file or directory (os error 2).  Please verify that version 0.5.2 or higher of the capnp executable is installed on your system. See https://capnproto.org/install.html" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by rajasekarv** [comment]
@errord you need to install [Cap'n Proto](https://capnproto.org/install.html) . It should solve the issue.

**Comment by errord** [comment]
Oh, sorry. I am negligent, and the reason is included in the error message.
