### ISSUE TITLE
Join contribute ?

### ISSUE THREAD

**Issue by uk0** [rajasekarv/native_spark#44]
Can I join the collaboration, I am eager to join, I think I can contribute

**Comment by iduartgomez** [comment]
Hello, @rajasekarv is a bit busy lately but hopefully will become more free soon.
You can join gitter if you wish maybe we can find out where you can help while we elaborate a more formalized plan or add more issues (which you are free to open btw).
Do tou have any particular interest in an area you would like to help or are knowledgeable about or nothing specially?

Cheers.

**Comment by rajasekarv** [comment]
Hi @uk0, I have been a bit busy lately. Now onwards, I will be a bit active. Please feel free to join us on Gitter and discuss where you can contribute. Some suggestion: You can generate good benchmarking suite to keep track of regressions and progress after some major commits/releases and to compare against apache spark to see when this framework is slow and how we can improve it.

**Comment by uk0** [comment]
thx  very nice

**Comment by uk0** [comment]
How to develop and test macos is not friendly, do you have any solution?

**Comment by iduartgomez** [comment]
Can't help with macOS development in Rust. 

As for a more general guideline, we should start opening and labeling issues and adding a contribution guideline IMO, we already have some work ahead planned and more to come but can improve on the details and guidance for people who would like to get on board. I can help with this too if you want me to help. We can talk a bit more about the details about priorities etc. on Gitter if you wish.

**Comment by iduartgomez** [comment]
@uk0 if you are still interested you can check the issue tracker for `good first issues`and `help wanted`, I am sorry can't helpo you out with macOS problems, you may find more luck in the official Rust forums (users.rust-lang.org) or Rust discord etc.

Hope you can work it out, any help is welcome here.
